List<List<String>> langList = [
  ["English", "en"],
  ["Russian", "ru"],
  ["Uzbekistan", "uz"],
  ["Afrikaans", "af"],
  ["Albanian", "sq"],
  ["Amharic", "am"],
  ["Arabic", "ar"],
  ["Armenian", "hy"],
  ["Azerbaijani", "az"],
  ["Basque", "eu"],
  ["Belarusian", "be"],
  ["Bengali", "bn"],
  ["Bosnian", "bs"],
  ["Bulgarian", "bg"],
  ["Catalan", "ca"],
  ["Cebuano", "ceb"],
  ["Chinese (Simplified)", "zh-CN"],
  ["Chinese (Traditional)", "zh-TW"],
  ["Corsican", "co"],
  ["Croatian", "hr"],
  ["Czech", "cs"],
  ["Danish", "da"],
  ["Dutch", "nl"],
  ["Esperanto", "eo"],
  ["Estonian", "et"],
  ["Finnish", "fi"],
  ["French", "fr"],
  ["Frisian", "fy"],
  ["Galician", "gl"],
  ["Georgian", "ka"],
  ["German", "de"],
  ["Greek", "el"],
  ["Gujarati", "gu"],
  ["Haitian Creole", "ht"],
  ["Hausa", "ha"],
  ["Hawaiian", "haw"],
  ["Hebrew", "iw"],
  ["Hindi", "hi"],
  ["Hmong", "hmn"],
  ["Hungarian", "hu"],
  ["Icelandic", "is"],
  ["Igbo", "ig"],
  ["Indonesian", "id"],
  ["Irish", "ga"],
  ["Italian", "it"],
  ["Japanese", "ja"],
  ["Javanese", "jw"],
  ["Kannada", "kn"],
  ["Kazakh", "kk"],
  ["Khmer", "km"],
  ["Korean", "ko"],
  ["Kurdish", "ku"],
  ["Kyrgyz", "ky"],
  ["Lao", "lo"],
  ["Latin", "la"],
  ["Latvian", "lv"],
  ["Lithuanian", "lt"],
  ["Luxembourgish", "lb"],
  ["Macedonian", "mk"],
  ["Malagasy", "mg"],
  ["Malay", "ms"],
  ["Malayalam", "ml"],
  ["Maltese", "mt"],
  ["Maori", "mi"],
  ["Marathi", "mr"],
  ["Mongolian", "mn"],
  ["Myanmar (Burmese)", "my"],
  ["Nepali", "ne"],
  ["Norwegian", "no"],
  ["Nyanja (Chichewa)", "ny"],
  ["Odia (Oriya)", "or"],
  ["Pashto", "ps"],
  ["Persian", "fa"],
  ["Polish", "pl"],
  ["Portuguese (Portugal, Brazil)", "pt"],
  ["Punjabi", "pa"],
  ["Romanian", "ro"],
  ["Samoan", "sm"],
  ["Scots Gaelic", "gd"],
  ["Serbian", "sr"],
  ["Sesotho", "st"],
  ["Shona", "sn"],
  ["Sindhi", "sd"],
  ["Sinhala (Sinhalese)", "si"],
  ["Slovak", "sk"],
  ["Slovenian", "sl"],
  ["Somali", "so"],
  ["Spanish", "es"],
  ["Sundanese", "su"]
];
